import os
import uuid
import shutil

try:
    import imageio_ffmpeg
    ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()
    bin_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".ffmpeg_bin")
    os.makedirs(bin_dir, exist_ok=True)
    is_windows = os.name == 'nt'
    ffmpeg_name = "ffmpeg.exe" if is_windows else "ffmpeg"
    local_ffmpeg = os.path.join(bin_dir, ffmpeg_name)
    if not os.path.exists(local_ffmpeg):
        shutil.copyfile(ffmpeg_exe, local_ffmpeg)
        if not is_windows:
            os.chmod(local_ffmpeg, 0o755)
    os.environ["PATH"] += os.pathsep + bin_dir
except ImportError:
    pass
from fastapi import FastAPI, UploadFile, File, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel

from core import process_video_pipeline, create_collage

app = FastAPI(title="Snipflow API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

os.makedirs("data/inputs", exist_ok=True)
os.makedirs("data/outputs", exist_ok=True)

jobs = {}

@app.get("/api/status/health-check")
async def health_check():
    return {"status": "ok"}

def background_processor(job_id: str, input_path: str, output_path: str, target_duration: float = 30.0, song_path: str | None = None, replace_audio: bool = False):
    try:
        print(f"Background task started for Job {job_id}")
        jobs[job_id]["status"] = "processing"
        
        def progress_cb(msg):
            jobs[job_id]["progress_msg"] = msg
            
        process_video_pipeline(input_path, output_path, target_duration=target_duration, song_path=song_path, replace_audio=replace_audio, progress_callback=progress_cb)
        
        if os.path.exists(output_path):
            jobs[job_id]["status"] = "completed"
            jobs[job_id]["output"] = output_path
            print(f"Job {job_id} completed successfully.")
        else:
            raise Exception("Output file was not generated by the pipeline.")
            
    except Exception as e:
        import traceback
        error_msg = str(e)
        print(f"Job {job_id} failed: {error_msg}")
        traceback.print_exc()
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = error_msg
    finally:

        if os.path.exists(input_path):
            try: os.remove(input_path)
            except: pass
        if song_path and os.path.exists(song_path):
            try: os.remove(song_path)
            except: pass

def background_collage_processor(job_id: str, input_paths: list[str], output_path: str, bg_color: str = "#f5f5f5", gap: int = 40, title: str = ""):
    try:
        print(f"Background collage task started for Job {job_id} with {len(input_paths)} images")
        jobs[job_id]["status"] = "processing"
        create_collage(input_paths, output_path, gap=gap, bg_color_hex=bg_color, title=title)
        
        if os.path.exists(output_path):
            jobs[job_id]["status"] = "completed"
            jobs[job_id]["output"] = output_path
            print(f"Collage Job {job_id} completed successfully.")
        else:
            raise Exception("Collage was not generated.")
    
    except Exception as e:
        import traceback
        error_msg = str(e)
        print(f"Job {job_id} failed: {error_msg}")
        traceback.print_exc()
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = error_msg
    finally:
        for path in input_paths:
            if os.path.exists(path):
                try:
                    os.remove(path)
                except:
                    pass
            